### ISSUE TITLE
ISO Failed to Download

### ISSUE THREAD

**Issue by dmcgill50** [windowsbox/packerwindows#7]
`PS C:\dev\code\packerwindows> packer build -var devtools=true windows10/packer.json
virtualbox-iso output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
    virtualbox-iso: Using file in-place: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Retrieving ISO
    virtualbox-iso: Error downloading: Error making HTTP GET request: 404 Not Found
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.`

**Comment by sneal** [comment]
On the workstation you're running Packer from check that you have a VBoxGuestAdditions.iso at the path listed in the error. This might be Packer/Vbox version mismatch. You can try a newer version of each or try setting the `guest_additions_url` property to a valid location, for example:

```
"guest_additions_url": "http://download.virtualbox.org/virtualbox/5.1.30/VBoxGuestAdditions_5.1.30.iso",
```

^ update the version to match your version of VBox.
